
from values import *
import weapons.melee as Melee
import weapons.gun as W
from weapons.area import Grenade
from weapons.area import Explosion




guns = {
    "M1911": W.Gun(
        name="M1911",
        clip_s = 8,
        fire_r = 2000,
        spread = 7,
        spread_r = 0.94,
        reload_r = 45,
        damage = 15,
        semi_auto = True,
        bullets_at_once = 1,
        shotgun = False,
        ammo_cap_lvlup = 1,
        image = "m1911.png",
        ammo = "INF",
        view = 0.0,
        handling = 0.7),
    "AR-15": W.Gun(
        name="AR-15",
        clip_s = 35,
        fire_r = 500,
        spread = 1,
        spread_r = 0.93,
        bullet_speed = 35,
        reload_r = 60,
        damage = 34,
        bullets_at_once = 1,
        shotgun = False,
        sounds = assault_rifle_sounds,
        ammo_cap_lvlup = 1,
        image = "m16.png",
        ammo = "7.62x39MM",
        piercing = True,
        view = 0.032,
        handling = 0.25,
        burst = True,
        burst_bullets = 3,
        burst_fire_rate = 2),
    "AK": W.Gun(
        name="AK47",
        clip_s = 30,
        fire_r = 520,
        spread = 3,
        spread_r = 0.94,
        bullet_speed = 25,
        reload_r = 60,
        damage = 34,
        bullets_at_once = 1,
        shotgun = False,
        sounds = assault_rifle_sounds,
        ammo_cap_lvlup = 1,
        image = "ak.png",
        ammo = "7.62x39MM",
        piercing = True,
        view = 0.03,
        handling = 0.35),
    "SCAR18": W.Gun(
        name="SCAR18",
        clip_s = 20,
        fire_r = 240,
        spread = 1,
        spread_r = 0.93,
        bullet_speed = 30,
        reload_r = 45,
        damage = 45,
        bullets_at_once = 1,
        shotgun = False,
        sounds = assault_rifle_sounds2,
        ammo_cap_lvlup = 1,
        image = "ak.png",
        ammo = "INF",
        piercing = True,
        view = 0.035,
        handling = 0.45),
    "M134 MINIGUN": W.Gun(
        name="M134 MINIGUN",
        clip_s = 999,
        fire_r = 2300,
        spread = 2,
        spread_r = 0.93,
        bullet_speed = 45,
        reload_r = 120,
        damage = 34,
        bullets_at_once = 1,
        shotgun = False,
        sounds = assault_rifle_sounds,
        ammo_cap_lvlup = 1,
        image = "m134.png",
        ammo = "5.56x45MM NATO",
        piercing = True,
        view = 0.03,
        handling = 0.1),
    "SPAS": W.Gun(
        name="SPAS-12",
        clip_s = 6,
        fire_r = 120,
        spread = 5,
        spread_per_bullet = 2,
        spread_r = 0.93,
        reload_r = 60,
        damage = 22,
        bullet_speed = 15,
        bullets_at_once = 8,
        shotgun = True,
        semi_auto = True,
        sounds = shotgun_sounds,
        ammo_cap_lvlup = 2,
        image = "spas12.png",
        ammo = "12 GAUGE",
        view = 0.01,
        handling = 0.2),
    "P90": W.Gun(
        name="P90",
        clip_s = 50,
        fire_r = 950,
        spread = 7,
        spread_r = 0.94,
        reload_r = 60,
        damage = 21,
        bullets_at_once = 1,
        shotgun = False,
        sounds = smg_sounds,
        ammo_cap_lvlup = 2,
        image = "p90.png",
        ammo = "9MM",
        view = 0.02,
        handling = 0.5),
    "GLOCK": W.Gun(
        name="GLOCK",
        clip_s = 20,
        fire_r = 350,
        spread = 3,
        spread_r = 0.92,
        reload_r = 30,
        damage = 27,
        semi_auto = False,
        bullets_at_once = 1,
        shotgun = False,
        ammo_cap_lvlup = 1,
        image = "glock.png",
        ammo = "45 ACP",
        view = 0.017,
        handling = 0.9,
        burst = True,
        burst_bullets = 3,
        burst_fire_rate = 3),
    "AWP": W.Gun(
        name="AWP",
        clip_s = 10,
        fire_r = 50,
        spread = 1,
        spread_r = 0.965,
        spread_per_bullet = 25,
        reload_r = 80,
        damage = 200,
        bullets_at_once = 1,
        sounds = sniper_rifle_sounds,
        bullet_speed = 55,
        shotgun = False,
        ammo_cap_lvlup = 1,
        image = "awp.png",
        ammo = "50 CAL",
        piercing = True,
        view = 0.045,
        handling = 0.15,
        semi_auto = True),
}
melees={

}
grenades={

}
__weapons_map={
    "gun":guns,
    "melee":melees,
    "grenade":grenades
}
